# .github/workflows/build-and-deploy.yml

name: Node.js CI

on:
  push:
    branches: [ master ]

permissions:
    contents: write
    
jobs:
  build:	
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          npm ci
          npm run build
          touch out/.nojekyll
          # configure the build here
      - name: Deploy
          # https://github.com/JamesIves/github-pages-deploy-action
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            branch: gh-pages
            folder: out

        # configure an external GitHub Pages deploy workflow here